server:
  port: 18281
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: admin  # 不配置 下面的配置文件名 也是无效的
  boot:
    admin:
      ui:
        title:  监控中心
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.0.25:8849
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS